use std::{fs, path::Path, process::Command};

fn main() {
    println!("cargo:rerun-if-changed=frontend/src");
    println!("cargo:rerun-if-changed=frontend/index.html");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/vite.config.ts");
    println!("cargo:rerun-if-changed=skills");

    bundle_skills();

    if frontend_bundle_is_forced_skip() {
        println!("cargo:warning=FORGE_SKIP_FRONTEND_BUILD=1: skipping Vite bundle");
        return;
    }

    install_frontend_deps();
    build_frontend();
}

fn frontend_bundle_is_forced_skip() -> bool {
    matches!(
        std::env::var("FORGE_SKIP_FRONTEND_BUILD").as_deref(),
        Ok("1") | Ok("true") | Ok("TRUE")
    )
}

fn bundle_skills() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest = Path::new(&out_dir).join("skills_bundle.rs");

    let skills_dir = Path::new(&manifest_dir).join("skills");
    let mut entries: Vec<(String, String, String)> = vec![];

    if skills_dir.is_dir() {
        let mut dirs: Vec<_> = fs::read_dir(&skills_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .collect();
        dirs.sort_by_key(|e| e.file_name());

        for entry in dirs {
            let skill_dir = entry.path();
            let skill_name = entry.file_name().to_string_lossy().to_string();
            // Accept both SKILL.md and SKILL.MD (macOS is case-insensitive but Linux is not)
            let skill_md = ["SKILL.md", "SKILL.MD"]
                .iter()
                .map(|name| skill_dir.join(name))
                .find(|p| p.exists());
            let Some(skill_md) = skill_md else { continue };
            let content = fs::read_to_string(&skill_md).unwrap_or_default();
            let description = parse_frontmatter_field(&content, "description")
                .unwrap_or_else(|| skill_name.clone());
            println!("cargo:rerun-if-changed={}", skill_md.display());
            entries.push((skill_name, description, content));
        }
    }

    let mut code = String::from(
        "// AUTO-GENERATED by build.rs — do not edit.\n\
         pub static SKILLS: &[(&str, &str, &str)] = &[\n",
    );
    for (name, description, content) in &entries {
        code.push_str(&format!(
            "    ({}, {}, {}),\n",
            rust_str_literal(name),
            rust_str_literal(description),
            rust_str_literal(content),
        ));
    }
    code.push_str("];\n");
    fs::write(&dest, code).unwrap();
}

/// Extracts a frontmatter field from a SKILL.MD file.
/// Frontmatter is delimited by `---` lines at the top of the file.
fn parse_frontmatter_field(content: &str, field: &str) -> Option<String> {
    let mut lines = content.lines();
    if lines.next()?.trim() != "---" {
        return None;
    }
    let prefix = format!("{}:", field);
    for line in lines {
        if line.trim() == "---" {
            break;
        }
        if let Some(rest) = line.strip_prefix(&prefix) {
            return Some(rest.trim().to_string());
        }
    }
    None
}

/// Encodes a string as a Rust byte-escaped double-quoted string literal.
fn rust_str_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn install_frontend_deps() {
    if Path::new("frontend/node_modules").exists() {
        return;
    }
    println!("cargo:warning=Installing frontend dependencies…");
    let status = Command::new("bun")
        .args(["install"])
        .current_dir("frontend")
        .status()
        .expect("`bun install` failed — is bun installed? https://bun.sh");
    assert!(status.success(), "bun install failed");
}

fn build_frontend() {
    println!("cargo:warning=Building frontend with Vite…");
    let out = Command::new("bun")
        .args(["run", "build"])
        .current_dir("frontend")
        .output()
        .expect("`bun run build` failed");

    if !out.status.success() {
        eprintln!("── stdout ──\n{}", String::from_utf8_lossy(&out.stdout));
        eprintln!("── stderr ──\n{}", String::from_utf8_lossy(&out.stderr));
        panic!("Frontend build failed");
    }
}
